#ifndef version_h
#define version_h

#define TELEHASH_VERSION_MAJOR 3
#define TELEHASH_VERSION_MINOR 0
#define TELEHASH_VERSION_PATCH 11
#define TELEHASH_VERSION ((TELEHASH_VERSION_MAJOR) * 10000 + (TELEHASH_VERSION_MINOR) * 100 + (TELEHASH_VERSION_PATCH))

#endif